version: '3'
services:
  web:
      image: nginx:alpine
      restart: always
      ports:
          - "80:80"
      volumes:
          - ./build/app/src:/var/www
          - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./log:/var/log/nginx
      environment: 
        - TZ=America/Sao_Paulo
      logging:
        options:
          max-size: "512m"
      links:
          - php
  php:
      image: php-mysql
      build: ./build/php
      restart: always
      user: 500:500
      logging:
        options:
          max-size: "512m"
      volumes:
          - ./build/app/src:/var/www
          - ./data/forum-cache:/var/www/forum/cache   
          - ./data/status:/var/www/status
          - ./log:/var/log/game
          - ./conf/php.conf:/usr/local/etc/php-fpm.d/www.conf
      environment: 
        - TZ=America/Sao_Paulo
      links: 
          - "db:ipmysql"
  db:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp --sql-mode=""
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: admin
      volumes: 
          - ./data/mysql:/var/lib/mysql
          # Start database script
          - ./build/app/db/:/docker-entrypoint-initdb.d/
          
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.24.0/24